
head:
	@echo "Bundling an I2P Router in your Application's Windows Installer" | tee README.md
	@echo "==============================================================" | tee -a README.md
	@echo "" | tee -a README.md

easy:
	@echo "The easy way" | tee -a README.md
	@echo "------------" | tee -a README.md
	@echo "" | tee -a README.md
	@echo "### Fetching a current I2P build, Every Time(TM)" | tee -a README.md
	@echo "" | tee -a README.md
	@echo "" | tee -a README.md

rdf:
	roqet -i sparql -e 'SELECT * WHERE { ?s ?p ?o } LIMIT 20' -D https://launchpad.net/i2p/trunk/+rdf

